param(
  [string]$SourceUrl = 'https://raw.githubusercontent.com/acfatah/malaysia-postcodes-data/refs/heads/main/dist/all-postcodes.json'
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$outputPath = Join-Path $projectRoot 'lib\data\malaysia_postcodes.dart'
$records = Invoke-RestMethod -Uri $SourceUrl
$stateNames = @{
  'Kuala Lumpur' = 'Wilayah Persekutuan Kuala Lumpur'
  'Labuan' = 'Wilayah Persekutuan Labuan'
  'Putrajaya' = 'Wilayah Persekutuan Putrajaya'
}

function Escape-Dart([string]$value) {
  return $value.Replace('\', '\\').Replace("'", "\'")
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by tool/update_malaysia_postcodes.ps1. Do not edit manually.')
$lines.Add('// Source: acfatah/malaysia-postcodes-data (MIT), derived from AsyrafHussin/malaysia-postcodes.')
$lines.Add('')
$lines.Add('class MalaysiaAddressOption {')
$lines.Add('  const MalaysiaAddressOption({')
$lines.Add('    required this.state,')
$lines.Add('    required this.city,')
$lines.Add('    required this.postcode,')
$lines.Add('  });')
$lines.Add('')
$lines.Add('  final String state;')
$lines.Add('  final String city;')
$lines.Add('  final String postcode;')
$lines.Add('}')
$lines.Add('')
$lines.Add('const malaysiaAddressOptions = <MalaysiaAddressOption>[')

foreach ($record in $records) {
  $state = if ($stateNames.ContainsKey($record.state)) { $stateNames[$record.state] } else { $record.state }
  $lines.Add("  MalaysiaAddressOption(state: '$(Escape-Dart $state)', city: '$(Escape-Dart $record.city)', postcode: '$(Escape-Dart $record.postcode)'),")
}
$lines.Add('];')

$outputDirectory = Split-Path -Parent $outputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[System.IO.File]::WriteAllLines($outputPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Output "Wrote $($records.Count) postcode records to $outputPath"
